### PR TITLE
Add hamburger menu

### LINKED ISSUE #23: Add menu styles for mobile
I am working on it right now.

### PR DESCRIPTION
**Pull request by pervoj**
closes #23

What do you think about that?

https://user-images.githubusercontent.com/71781857/166700408-533e02ff-a798-457e-9fba-30b830be7fc5.mp4

I played around with the animations a bit.

### CODE REVIEW

**Comment by nahuelwexd** [comment]
cc @Suzie97

**Review by colinkiama — CHANGES_REQUESTED** [review]
I like the animation, it's pretty cool.

[However I did say](https://github.com/colinkiama/vala-www/issues/23#issuecomment-1116955156):
> I think that it would be nice to have one when JavaScript is enabled on mobile devices.

I should have been more clear that [progressive enhancement](https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement) should have been used.

Overall this is a great contribution! If you feel like making the links clickable without JS is too hard, just let me know. I can do that part myself.

**Comment by nahuelwexd** [comment]
The hack to achieve this kind of menus without JS seems pretty clever to me, but the problem is that you end up with HTML that is not semantic :eyes:

Perhaps we should keep this type of menu only for Javascript enabled users, and use <noscript> to load a fallback layout similar to the Rust one @Suzie97 mentioned.

**Comment by pervoj** [comment]
I have two ideas on how to do this.

1. Using JS to add `js-enabled` class to `<body>` (better for me)
2. Use `<noscript>` tag to load special styles

What do you think is better? Or do you have a better idea?

**Comment by colinkiama** [comment]
I think that the first one is better

**Comment by colinkiama** [comment]
Yeah, this is great. Just need some a bit more spacing (maybe 0.75rem or 1rem?) above the links then I'm happy to merge it in.

**Comment by pervoj** [comment]
So this is the final version:

Snímek z 2022-05-04 19-19-48 Snímek z 2022-05-04 19-20-14

**Review by colinkiama — APPROVED** [review]

**Comment by pervoj** [comment]
Oh wait, you merged before pushing the last version :)

**Comment by colinkiama** [comment]
lmao

**Comment by colinkiama** [comment]
Welp, time for a new PR I guess

**Comment by nahuelwexd** [comment]
@pervoj mark as "Draft" the next time, so it doesn't get merged prematurely

**Pull request merged**
