### PR TITLE
Use vala.dev

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by nahuelwexd** [comment]
Already had some changes in local for this. Requires a bit more changes than just updating config.toml

**Comment by nahuelwexd** [comment]
Let's see if Colin agrees in order to merge this

**Comment by dar5hak** [comment]
Ha! Beat me to it!

**Review by colinkiama — APPROVED** [review]

**Comment by pervoj** [comment]
Any updates on this?

closes #6

**Comment by colinkiama** [comment]
Lol the issue has already been linked

**Pull request merged**
