### PR TITLE
WIP: Fill home page with content

### PR DESCRIPTION
**Pull request by lw64**

### CODE REVIEW

**Comment by lw64** [comment]
The style and obviously the icons aren't final yet.

**Comment by pervoj** [comment]
Maybe include Discord too.

**Comment by lw64** [comment]
> Maybe include Discord too.

I think we need to somehow discuss what purpose each platform actually has. At the moment there are just thousand options without much thoughts behind. I think discord is for the community.

**Comment by colinkiama** [comment]
> > Maybe include Discord too.
> 
> I think we need to somehow discuss what purpose each platform actually has. At the moment there are just thousand options without much thoughts behind. I think discord is for the community though.

This discussion would be a great place for talking about these kinds of things: https://github.com/colinkiama/vala-www/discussions/12

**Comment by lw64** [comment]
To make it clear. This MR is just about the content. Obviously the design and styling surrounding the text needs to be updated and adjusted. But I am not feeling really comfortable with that and think especially with design others are more experienced. So I would really like to have some help from that side.

Another thing is that of course some feedback about the content would be maybe good.

**Comment by colinkiama** [comment]
Closes #62.

**Comment by colinkiama** [comment]
> To make it clear. This MR is just about the content. Obviously the design and styling surrounding the text needs to be updated and adjusted. But I am not feeling really comfortable with that and think especially with design others are more experienced. So I would really like to have some help from that side.
> 
> Another thing is that of course some feedback about the content would be maybe good.

For the sake of convenience, this MR is now will also include the design and styling.

**Comment by colinkiama** [comment]
Screen Shot 2022-06-19 at 17 14 38
Screen Shot 2022-06-19 at 17 15 24

**Comment by pervoj** [comment]
> Latest changes to the "Why Vala?" section
@colinkiama would be better to remove the white space bellow the text

**Comment by colinkiama** [comment]
I do think that the padding at the bottom is too much but completely removing would look even more weird

**Comment by colinkiama** [comment]
Updated "Why Vala?" section and "What's new section"
Screen Shot 2022-06-19 at 18 56 39
Screen Shot 2022-06-19 at 18 56 43

**Comment by pervoj** [comment]
> I do think that the padding at the bottom is too much but completely removing would look even more weird

@colinkiama I don't mean completely removing it, but change it to match the top one.

**Comment by colinkiama** [comment]
Okay, are the latest changes okay?

**Comment by pervoj** [comment]
I think this is better:

obrazek

this is 2rem

**Comment by colinkiama** [comment]
How about 2.5rem? Sorry, 2rem looks a bit too cramped to me

**Comment by pervoj** [comment]
Okay, a compromise :)

**Comment by colinkiama** [comment]
All the sections are now added except the Showcase.
Screen Shot 2022-06-25 at 22 45 45
Screen Shot 2022-06-25 at 22 45 56
Screen Shot 2022-06-25 at 22 46 01
Screen Shot 2022-06-25 at 22 46 07

**Pull request merged**
