### PR TITLE
use woff and woff2 for fonts instead of ttf

### PR DESCRIPTION
**Pull request by nahuelwexd**
WOFF and WOFF2 provide a higher level of compression than TTF, in addition to being specifically designed for the web.

According to “Can I use”, 93% of users have browsers that support WOFF2, however, WOFF is provided as fallback.

### CODE REVIEW

**Review by colinkiama — APPROVED** [review]
Awesome!

**Comment by dar5hak** [comment]
But IE wa mou shindeiru, and Opera Mini doesn't do webfonts anyway. It won't be too much of a stretch to just ship woff2 and let these fall back to system fonts.

**Comment by nahuelwexd** [comment]
Inter provides you with woff and woff2 in its zip, so adding both wasn't really any more work.

I see no reason to only provide woff2

**Comment by dar5hak** [comment]
Fair enough

**Pull request merged**
